version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/app:/app/data  # Mount the directory
      - ./api/food_data.csv:/app/food_data.csv
    environment:
      DATABASE_URL: "sqlite:///./data/foodtracker.db" # Database file within the mounted directory

  vision:
    build: ./vision
    ports:
      - "8001:8000"
    volumes:
      - ./vision/app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
