version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    env_file: .env

  relational:
    build: ./relational
    ports:
      - "8002:8000"
    volumes:
      - ./relational/app:/app/app
      - ./data:/app/data
      - ./relational/food_data.csv:/app/food_data.csv
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - vector

 

  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/app:/app/app
    env_file: .env
    environment:
      OLLAMA_MODEL: ${CHAT_MODEL}
    depends_on:
      - relational vector:
    build: ./vector_service
    ports:
      - "8003:8000"
    volumes:
      - ./vector_service/app:/app/app
    env_file: .env
    environment:
      OLLAMA_MODEL: ${EMBED_MODEL}
    depends_on:
      - qdrant

  vision:
    build: ./vision
    ports:
      - "8001:8000"
    volumes:
      - ./vision/app:/app/app
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  qdrant_storage:
